import React from 'react';
import BrandIcon from '@/components/brand-icon';

type Props = {
  className?: string;
  title?: string;
} & Record<string, any>;

const make = (name: string) => (props: Props) => (
  <BrandIcon name={name} className={props.className} title={props.title} decorative />
);

// Lucide-kompatibler Typ, damit bestehende Stellen kompilieren
export type LucideIcon = (props: Props) => JSX.Element;

// Common icon wrappers mapped to brand icon names (kebab-case)
export const Calendar = make('calendar');
export const Flag = make('flag');
export const AlertTriangle = make('alert');
export const CheckCircle = make('check');
export const CheckCircle2 = make('check-circle-2');
export const Clock = make('clock');
export const Filter = make('filter');
export const Search = make('search');
export const Code = make('code');
export const Code2 = make('code-2');
export const Package = make('package');
export const FileText = make('document');
export const Newspaper = make('newspaper');
export const Wrench = make('wrench');
export const AlertCircle = make('alert-circle');
export const TrendingUp = make('trending-up');
export const TrendingDown = make('trending-down');
export const Globe = make('globe');
export const Brain = make('intelligence');
export const Loader2 = make('loader');
export const Loader = make('loader');
export const ChevronDown = make('chevron-down');
export const ChevronUp = make('chevron-up');
export const Lightbulb = make('lightbulb');
export const Check = make('check');
export const Moon = make('moon');
export const Sun = make('sun');
export const Dot = make('dot');
export const Circle = make('circle');
export const GripVertical = make('grip-vertical');
export const X = make('x');
export const Menu = make('menu');
export const ChevronLeft = make('chevron-left');
export const ChevronRight = make('chevron-right');
export const MoreHorizontal = make('more-horizontal');
export const ExternalLink = make('external-link');
export const Link = make('link');
export const Copy = make('copy');
export const Key = make('key');
export const Shield = make('shield');
export const Lock = make('lock');
export const Unlock = make('unlock');
export const ClipboardList = make('clipboard-list');
export const Database = make('database');
export const Settings = make('settings');
export const Rocket = make('rocket');
export const Target = make('target');
export const Eye = make('eye');
export const Hash = make('hash');
export const Download = make('download');
export const RefreshCw = make('refresh');
export const MessageSquare = make('message');
export const MessageCircle = make('message-circle');
export const BarChart3 = make('chart');
export const BarChart = make('bar-chart');
export const Sparkles = make('spark');
export const Heart = make('heart');
export const Users = make('users');
export const UserPlus = make('user-plus');
export const LogIn = make('log-in');
export const LogOut = make('log-out');
export const Play = make('play');
export const PlayCircle = make('play-circle');
export const Pause = make('pause');
export const RotateCcw = make('rotate-ccw');
export const Trash2 = make('trash');
export const Plus = make('plus');
export const Edit = make('edit');
export const History = make('history');
export const Server = make('server');
export const Scale = make('scale');
export const DollarSign = make('dollar-sign');
export const Gavel = make('gavel');
export const Archive = make('archive');
export const FileSearch = make('file-search');
export const FileIcon = make('file');
export const FileCheck = make('file-check');
export const Share2 = make('share');
export const Mail = make('mail');
export const Send = make('send');
export const Trash = make('trash');
export const Building2 = make('building-2');
export const Building = make('building');
export const User = make('user');
export const UserCircle = make('user-circle');
export const UserCheck = make('user-check');
export const EyeOff = make('eye-off');
export const Crown = make('crown');
export const Star = make('star');
export const Award = make('award');
export const TestTube = make('test-tube');
export const ArrowLeft = make('arrow-left');
export const ArrowRight = make('arrow-right');
export const ArrowUpRight = make('arrow-up-right');
export const Type = make('type');
export const VolumeX = make('volume-x');
export const Volume2 = make('volume-2');
export const MousePointer = make('mouse-pointer');
export const PieChart = make('pie-chart');
export const Activity = make('activity');
export const LineChart = make('line-chart');
export const BookOpen = make('book-open');
export const Book = make('book');
export const Bookmark = make('bookmark');
export const Bell = make('bell');
export const FolderSync = make('folder-sync');
export const FolderOpen = make('folder-open');
export const Zap = make('zap');
export const Home = make('home');
export const Layers = make('layers');
export const LayoutDashboard = make('layout-dashboard');
export const Clipboard = make('clipboard');
export const ArrowUp = make('arrow-up');
export const ArrowDown = make('arrow-down');
export const Minus = make('minus');
export const Palette = make('palette');
export const Upload = make('upload');
export const Save = make('save');
export const Image = make('image');
export const Folder = make('folder');

// Backwards-compat aliases
export const CalendarIcon = Calendar;
